#!/usr/bin/python3

import pygame
from my_class import Screen_enum, Color, Screen
from Snake import Snake
from Main import Main
from Over import Over
from Help import Help

def draw(window: pygame.Surface, snake: Snake):
    for y in range(len(snake.map)):
        for x in range(len(snake.map[y])):
            if snake.map[y][x] > 0:
                if snake.map[y][x] == snake.head_life:
                    pygame.draw.rect(window, Color.head, (x * 20, y * 20, 20, 20))
                else:
                    pygame.draw.rect(window, Color.body, (x * 20, y * 20, 20, 20))
            if snake.map[y][x] == -1:
                pygame.draw.rect(window, Color.apple, (x * 20, y * 20, 20, 20))
    pygame.display.update()

def main_loop(window: pygame.Surface):
    game = Main()
    clock = pygame.time.Clock()
    while Screen.screen == Screen_enum.Main:
        game.update(pygame.event.get())
        game.draw(window)
        clock.tick(20)

def game_loop(window: pygame.Surface):
    snake = Snake(40, 30)
    snake.place_apple()
    snake.place_snake()
    clock = pygame.time.Clock()
    while Screen.screen == Screen_enum.Game:
        window.fill(Color.background)
        snake.update(pygame.event.get())
        draw(window, snake)
        clock.tick(3)

def over_loop(window: pygame.Surface):
    game = Over()
    clock = pygame.time.Clock()
    while Screen.screen == Screen_enum.Over:
        game.update(pygame.event.get())
        game.draw(window)
        clock.tick(20)
    
def help_loop(window: pygame.Surface):
    help = Help()
    clock = pygame.time.Clock()
    while Screen.screen == Screen_enum.Help:
        help.update(pygame.event.get())
        help.draw(window)
        clock.tick(20)

def main():
    pygame.init()
    window_width = 800
    window_height = 600
    window = pygame.display.set_mode((window_width, window_height))
    pygame.display.set_caption("Snake Game")
    while(Screen.screen != Screen_enum.Exit):
        if Screen.screen == Screen_enum.Main:
            main_loop(window)
        if Screen.screen == Screen_enum.Game:
            game_loop(window)
        if Screen.screen == Screen_enum.Over:
            over_loop(window)
        if Screen.screen == Screen_enum.Help:
            help_loop(window)
    pygame.quit()

main()
